spring.application.name=api
# Tells Spring Boot to always run schema.sql and data.sql on startup
spring.sql.init.mode=always

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jobbase-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Let Hibernate automatically create/update the tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update

# Print the SQL queries in the console
spring.jpa.show-sql=true
